version: "3"

services:
    laravel:
        image: laravel:latest
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        container_name: laravel
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.laravel.rule=Host(`laravel.techcode.cloud`)"
            - "traefik.http.routers.laravel.entrypoints=web"
            - "traefik.http.services.laravel.loadbalancer.server.port=80"
            - "traefik.docker.network=traefik_webgateway"

        networks:
            - traefik_webgateway

networks:
    traefik_webgateway:
        external: true
